Processing media item (65/87: /media/simon/VERBATIM/Backup af billeder 14022018/Blandede billeder 2016/20161202_215111.jpg
Processing media item (66/87: /media/simon/VERBATIM/Backup af billeder 14022018/Blandede billeder 2016/20161202_215117.jpg
Processing media item (67/87: /media/simon/VERBATIM/Backup af billeder 14022018/Blandede billeder 2016/20161202_215132.mp4
Processing media item (68/87: /media/simon/VERBATIM/Backup af billeder 14022018/Blandede billeder 2016/20161202_215236.mp4
Processing media item (69/87: /media/simon/VERBATIM/Backup af billeder 14022018/Blandede billeder 2016/20161202_215325.mp4
Processing media item (70/87: /media/simon/VERBATIM/Backup af billeder 14022018/Blandede billeder 2016/20161202_215439.jpg
Traceback (most recent call last):
  File "/home/simon/Projects/Week-by-week-learning/GooglePhotosUploadApp/create_albums.py", line 117, in <module>
    upload_response = service.mediaItems().batchCreate(body=upload_request).execute()
  File "/home/simon/.pyenv/versions/week-by-week/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/simon/.pyenv/versions/week-by-week/lib/python3.6/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json returned "Request must contain a valid upload token.">

Process finished with exit code 1